### ISSUE TITLE
Port cartodb-java-client to .NET question

### ISSUE THREAD

**Issue by ahuarte47** [CartoDB/cartodb-java-client#7]
Hi, the https://github.com/thedatarepublic/CartoDBClientDotNET repo contains a very old CartoDB client in .NET.

I would like know if there are plans to port the cartodb-java-client to .NET in order to  develop reader/writer data converters in .NET applications.

Thanks in advance
Alvaro

**Comment by javisantana** [comment]
For the moment we have no plans for this, in any case the API interface didn't change so much so that library probably still work, did you try it?

**Comment by ahuarte47** [comment]
Hi Javi, thanks for your reply!

No, I did not tried it. My plans are develop a .NET CartoDB data manager to integrate it in a desktop free CAD/GIS data converter (Geobide Converter - http://www.geobide.es/geoconverter/ ).

![image](https://cloud.githubusercontent.com/assets/5576272/7387575/81af11e4-ee5e-11e4-931e-59a995fe3ae2.png)

I will try it!
Best Regards
Alvaro

**Comment by ahuarte47** [comment]
Hi Javi, I am tested your SQL API and I works fine using single http webrequests. I dont need write any .NET wrapper to manage the CartoDB datasets.

At this point I would love to give you congratulations on your excellent platform!!! I'm excited to learn it and know to use their APIs.

Best Regards
Alvaro

**Comment by javisantana** [comment]
as you say it's easy to make http calls to sql api and get results but there are some reasons why we created some api wrappers:

- if the sql is too large (more than 2k) a POST needs to be used
- if the sql is writing data is better to use POST. We manage the cache in that case but it's always better to do writes with POST
- api_key management, disallow the use of api_key with http (instead of https)

**Comment by ahuarte47** [comment]
Thanks! I study your advices

**Comment by javisantana** [comment]
in any case, let us know about your project in the catodb mailing list https://groups.google.com/forum/#!forum/cartodb

**Comment by ahuarte47** [comment]
ok, thanks, I will do it! I close this issue.

Best Regards
Alvaro

**Comment by ahuarte47** [comment]
Hi Javi, I published an article about my experience using your platform:
http://gisconletras.blogspot.com.es/2015/05/import-data-to-cartodb-with-geobide.html

Now, I present it in the catodb mailing list.

Thanks and congratulations for your work!
Alvaro
